//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTotal.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTotal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No antiviruses marked it as malicious.
        /// </summary>
        public static string _0detects {
            get {
                return ResourceManager.GetString("0detects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folder in settings window!.
        /// </summary>
        public static string AddFolderForce {
            get {
                return ResourceManager.GetString("AddFolderForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding folder.
        /// </summary>
        public static string AddingFolder {
            get {
                return ResourceManager.GetString("AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoTotal — Settings.
        /// </summary>
        public static string ATSettings {
            get {
                return ResourceManager.GetString("ATSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autorun app with Windows.
        /// </summary>
        public static string Autorun {
            get {
                return ResourceManager.GetString("Autorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  antiviruses marked file as malicious.
        /// </summary>
        public static string AVsDetected {
            get {
                return ResourceManager.GetString("AVsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block files until scanned.
        /// </summary>
        public static string BlockFiles {
            get {
                return ResourceManager.GetString("BlockFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change VirusTotal API key.
        /// </summary>
        public static string ChangeVTKey {
            get {
                return ResourceManager.GetString("ChangeVTKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing VirusTotal API key.
        /// </summary>
        public static string ChangingVTKey {
            get {
                return ResourceManager.GetString("ChangingVTKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking key.
        /// </summary>
        public static string CheckingKey {
            get {
                return ResourceManager.GetString("CheckingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File %name% wasn&apos;t scanned! Check internet connection!.
        /// </summary>
        public static string CheckInternetConnection {
            get {
                return ResourceManager.GetString("CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while checking key: .
        /// </summary>
        public static string CheckKeyError {
            get {
                return ResourceManager.GetString("CheckKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  is clean!.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  is dangerous!.
        /// </summary>
        public static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete file.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-existing folder was deleted from the list.
        /// </summary>
        public static string DisappearedFolder {
            get {
                return ResourceManager.GetString("DisappearedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This file doesn&apos;t exist.
        /// </summary>
        public static string FileDoesntExist {
            get {
                return ResourceManager.GetString("FileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is more than 650 MB, it can&apos;t be scanned on VirusTotal! Be cautious, make sure you can trust the source!.
        /// </summary>
        public static string FileTooBig {
            get {
                return ResourceManager.GetString("FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish first setup!.
        /// </summary>
        public static string FinishFirstSetup {
            get {
                return ResourceManager.GetString("FinishFirstSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders list.
        /// </summary>
        public static string FoldersList {
            get {
                return ResourceManager.GetString("FoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to get?.
        /// </summary>
        public static string HowToGet {
            get {
                return ResourceManager.GetString("HowToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid key!.
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VirusTotal is scanning .
        /// </summary>
        public static string IsScanning {
            get {
                return ResourceManager.GetString("IsScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key has been changed!.
        /// </summary>
        public static string KeyChanged {
            get {
                return ResourceManager.GetString("KeyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - folder.
        /// </summary>
        public static string MinusFolder {
            get {
                return ResourceManager.GetString("MinusFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + folder.
        /// </summary>
        public static string PlusFolder {
            get {
                return ResourceManager.GetString("PlusFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VirusTotal is processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program will automatically start with Windows! You can change this in settings.
        /// </summary>
        public static string ProgramWillAutostart {
            get {
                return ResourceManager.GetString("ProgramWillAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File %name% wasn&apos;t scanned! Unfortunately, the VirusTotal API usage limit has been reached. Please try scanning again after some time. Alternatively, create a new VirusTotal account and update the key to a new one..
        /// </summary>
        public static string QuotaExceeded {
            get {
                return ResourceManager.GetString("QuotaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoTotal — Scan error.
        /// </summary>
        public static string ScanError {
            get {
                return ResourceManager.GetString("ScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan file....
        /// </summary>
        public static string ScanFile {
            get {
                return ResourceManager.GetString("ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanning .
        /// </summary>
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show report.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program was started in background, use tray icon for interacting.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  is suspicious!.
        /// </summary>
        public static string Suspicious {
            get {
                return ResourceManager.GetString("Suspicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoTotal — VirusTotal API limit.
        /// </summary>
        public static string TitleLimit {
            get {
                return ResourceManager.GetString("TitleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading %name% to VirusTotal.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/ImMALWARE/AutoTotal/wiki/Obtaining-VirusTotal-API-Key.
        /// </summary>
        public static string WikiLink {
            get {
                return ResourceManager.GetString("WikiLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoTotal is started in background.
        /// </summary>
        public static string WorkingInBackground {
            get {
                return ResourceManager.GetString("WorkingInBackground", resourceCulture);
            }
        }
    }
}
